
ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO spring_jdbc_oracle CONTAINER=CURRENT;
GRANT CREATE SESSION TO spring_jdbc_oracle CONTAINER=CURRENT;
GRANT RESOURCE TO spring_jdbc_oracle CONTAINER=CURRENT;

ALTER USER spring_jdbc_oracle QUOTA 100M ON USERS;
